### ISSUE TITLE
fail to open .env

### ISSUE THREAD

**Issue by shavo007** [janders223/serverless-offline-ssm#3]
hi,

get issue now when running locally:

```
  Error --------------------------------------------------

  ENOENT: no such file or directory, open '.env'

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Stack Trace --------------------------------------------

Error: ENOENT: no such file or directory, open '.env'
    at Object.fs.openSync (fs.js:663:18)
    at Object.fs.readFileSync (fs.js:568:33)
    at readEnvFile (/Users/slee/projects/adv-invoice/node_modules/serverless-offline-ssm/dist/index.js:6:43)
    at bluebird.Promise.resolve (/Users/slee/projects/adv-invoice/node_modules/serverless-offline-ssm/dist/index.js:17:19)
    at start (/Users/slee/projects/adv-invoice/node_modules/serverless-offline-ssm/dist/index.js:16:29)
```

script command is 

```
DEBUG=jwks SLS_DEBUG=*  sls invoke local --watch --function xxx --path fixtures/xxx.json --stage dev
```

deps

```
serverless-offline-ssm: 1.0.4
```

**Comment by janders223** [comment]
The plugin looks for a `.env` file in the project root directory that lists the SSM params that you are looking to replace. The error states that it cannot find that file.

**Comment by shavo007** [comment]
i have .env file at root dir. ill close for now as it seems to be working this morning.

thanks.
